# Generated by Django 4.1.3 on 2022-11-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Hash', models.TextField()),
            ],
        ),
    ]
