# Generated by Django 4.1.3 on 2022-11-24 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Create_Time', models.DateTimeField()),
                ('Password_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.passwords')),
            ],
        ),
    ]
