# Generated by Django 4.1.3 on 2022-11-28 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webstore.passwords'),
        ),
    ]
