# Generated by Django 4.1.3 on 2022-11-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='InCategories',
            fields=[
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webstore.products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.categories')),
            ],
            options={
                'unique_together': {('product', 'category')},
            },
        ),
    ]
