# Generated by Django 4.1.3 on 2022-11-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateTimeField()),
                ('Address', models.TextField()),
                ('Status', models.CharField(choices=[('PS', 'Processing'), ('PG', 'Packaging'), ('SH', 'Shipping'), ('PU', 'Pickup'), ('DV', 'Delivered')], default='PS', max_length=2)),
                ('Delivery', models.DateTimeField(blank=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.users')),
            ],
        ),
    ]
