# Generated by Django 4.1.3 on 2022-11-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0004_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('Stock', models.IntegerField()),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
